name: emotion_streaming

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - pip=21.0.1
  - pip:
    - opencv_python==4.5.1.48
    - tensorflow-cpu==2.4.0
    - Pillow==8.1.0
    - aiortc==1.0.0
    - av==8.0.2
    - numpy==1.19.5
    - streamlit==0.74.1
    - streamlit_webrtc==0.6.0
    - typing_extensions==3.7.4.3
    - imutils

