name: emotion
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - pip=20.3.3
  - pip:
    - pytest==6.2.1
    - pylint==2.6.0
    - flask==1.1.2
    - gunicorn==20.0.4
    - tensorflow==2.4.0
    - imutils==0.5.4
    - numpy==1.19.5
    - opencv-python==4.5.1.48
    - matplotlib==3.3.3
    - argparse==1.4.0
    - scipy==1.6.0
    - scikit-learn==0.24.1
    - pillow==8.1.0
    - streamlit==0.74.1
    - streamlit-webrtc
